/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/components` | `/components`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/components/card/card` | `/components/card/card`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/components/card/styles` | `/components/card/styles`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/styles` | `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/components` | `/components`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/components/card/card` | `/components/card/card`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/components/card/styles` | `/components/card/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(home)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/styles${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/components${`?${string}` | `#${string}` | ''}` | `/components${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/components/card/card${`?${string}` | `#${string}` | ''}` | `/components/card/card${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/components/card/styles${`?${string}` | `#${string}` | ''}` | `/components/card/styles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/components` | `/components`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/components/card/card` | `/components/card/card`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/components/card/styles` | `/components/card/styles`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
